### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by ferremayorsantodomingo** [grantwinney/hide-comments-in-chrome-sites#26] opened 2019-06-24 14:57 UTC
Here's a new site I'd like you to consider blocking:

https://www.facebook.com/ferremayoronline/photos/a.2191298614437226/2363269700573449/?type=3&theater

(please include any other relevant details)

**Comment by grantwinney** [comment] 2019-08-14 13:28
Closing as dupe of https://github.com/grantwinney/hide-comments-in-chrome-sites/issues/25

**Closed by grantwinney** 2019-08-14 13:28 UTC
